### ISSUE TITLE
how to run it ？

### ISSUE THREAD

**Issue by sweetlj** [TjFish/COVID-19-Dashboard#1]
学长，应该怎么启动啊，能不能在readme后面加个启动方法

**Comment by TjFish** [comment]
已加😘

**Comment by TjFish** [comment]
## Run it

运行项目前，需要先安装npm，由于nodejs自带npm，所以直接安装[nodejs](https://nodejs.org/zh-cn/) 即可。

下载源代码后，项目分为两个子项目

- Dashboard

```powershell
# 工作目录
cd Dashboard 
# 安装依赖
npm install 
# 启动server
npm run server 
```

​	open browser  http://localhost:8080/

- 3d

```powershell
cd 3d
npm install 
npm run dev
```

​	open browser http://localhost:1234/

**最后，本项目代码混乱，赶工明显，不建议继续开发。谨希望能为学弟学妹们提供一些思路~~**

**祝好！**

**Comment by TjFish** [comment]
> 学长，应该怎么启动啊，能不能在readme后面加个启动方法

已加 😘

**Comment by sweetlj** [comment]
谢谢学长
